# Generated by Django 4.0.1 on 2022-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0004_tattoo_time_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='numAvail',
            field=models.IntegerField(default=0, verbose_name='numAvail'),
        ),
    ]
