# Generated by Django 4.0.1 on 2022-06-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0005_tattoo_numavail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='colored',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='colored'),
        ),
    ]
