# Generated by Django 4.0.1 on 2022-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='numAvail',
            field=models.IntegerField(default=0.0, verbose_name='numAvail'),
        ),
    ]
