# Generated by Django 4.0.1 on 2022-06-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transaction_numavail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='numAvail',
        ),
    ]
