# Generated by Django 4.0.1 on 2022-06-15 10:45

from django.db import migrations, models
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_transaction_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(default='uploads/Cases.png', upload_to=transaction.models.nameFile, verbose_name='image'),
        ),
    ]
