# Generated by Django 4.0.1 on 2022-06-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_transaction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
