# Generated by Django 4.0.1 on 2022-06-16 02:29

from django.db import migrations, models
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_transaction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paymentImage',
            field=models.ImageField(default='uploads/Cases.png', upload_to=transaction.models.nameFile, verbose_name='paymentImage'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
