# Generated by Django 4.0.1 on 2022-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
    ]
