# Generated by Django 4.0.1 on 2022-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_design_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='color',
        ),
        migrations.AddField(
            model_name='design',
            name='colored',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='colored'),
        ),
    ]
