# Generated by Django 4.0.1 on 2022-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gcash'),
        ),
    ]
